### ISSUE TITLE
maven in Actions and submitting new version in the maven repo

### ISSUE THREAD

**Issue by jbytecode** [jbytecode/rcaller#48]
Hi all, 

We have already CI integration so after each single commit we show up an image that indicates whether RCaller successfully compiles or not, in the README.md file.

Now, we need these:

- Can somebody setup a maven action in Actions section with all tests are passed?
- Can somebody submit the latest release into Maven repos?
- Can somebody setup a release tagger in Actions, so we can serve compiled jars with diff's compared to the previous release?

Thank you in advance.

**Comment by jbytecode** [comment]
@Kopilov Can you help with one of these topics?

**Comment by Kopilov** [comment]
@jbytecode I will try little later.
I do not have any experience with GitHub Actions today (in our business we use GitLab CI with self-hosted GitLab server).
I am ready to learn how to use GitHub Actions to make our project better.

**Comment by jbytecode** [comment]
> @jbytecode I will try little later.
> I do not have any experience with GitHub Actions today (in our business we use GitLab CI with self-hosted GitLab server).
> I am ready to learn how to use GitHub Actions to make our project better.

Okay thank you in advance

**Comment by Kopilov** [comment]
Hello @jbytecode 
I have some results but not everything is fine.

In [citest](https://github.com/Kopilov/rcaller/tree/citest) there are two simple workflows, for compile and for test. (As you said, our project have CI integration that indicates whether RCaller successfully compiles or not and it is marked as "build" on the [badge](https://api.travis-ci.org/jbytecode/rcaller.svg?branch=master), but actually we have `script: mvn test` in Travis pipeline. So we already have "section with all tests are passed" but without GitHub Actions. May be that is enough, but I was interested in trying GitHub Actions with you.)

The main problem with running tests in GitHub Actions CI is that Utf8CharactersTest fails and I can not found the reason. I have disabled it in [citest](https://github.com/Kopilov/rcaller/tree/citest) branch to get "test passing" badge. In [cidebug](https://github.com/Kopilov/rcaller/tree/cidebug) branch I tried to fix the problem but no solution is found. I can see only that R prints `NA` in the output XML file instead of expected string. And I have found that it can be printed by [iconv](https://rdrr.io/r/base/iconv.html) but have not found any reason. In pipeline there is separate task that prints correct result from R console.

Here is the [Dockerfile](https://gist.github.com/Kopilov/f615925e4dfc90918e7eb8c84da1bced) with very similar commands sequence and it pass all tests correctly. The main difference with GitHub is that Ubuntu 18.4 (that [is used](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on) in Actions) should have R-3.4.4 but in the workflow log we can see "r-base is already the newest version (4.0.2-1.1804.0)." Just now I do not have R-4.0.2 installed to test.

**Comment by jbytecode** [comment]
Hi @Kopilov , thank you for your great effort. The test Utf8CharactersTest() is really problematic, it passes in my Linux machine however it fails in my mac os. The failure message starts with

Utf8CharactersTest(com.github.rcaller.UTF8Test)  Time elapsed: 0.282 sec  <<< FAILURE!
java.lang.AssertionError: 
	at org.junit.Assert.fail(Assert.java:91)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at org.junit.Assert.assertTrue(Assert.java:54)
	at com.github.rcaller.UTF8Test.Utf8CharactersTest(UTF8Test.java:33)

**Comment by jbytecode** [comment]
any changes in this test is appreciated and is accepted. please prepare pull requests to handle this problem.

**Comment by Kopilov** [comment]
So, as I wrote in another thread, Utf8CharactersTest actually depends on the current locale (LANG environment variable).
Docker-based example above is also not absolutely correct (it should have `ENV LANG=en_US.UTF-8` line together (or instead of) `RUN echo "LANG=en_US.UTF-8" > /etc/default/locale`). But by default in Docker we have LANG=POSIX, in GitHub Actions we have LANG=C.UTF-8.

Our test works correctly with en_US.UTF-8 locale (or any another explicit language), passes (may by, false positive) with LANG=POSIX and does not work (why?) with LANG=C.UTF-8.

@jbytecode please, control in Mac OS what LANG value (and also what `locale` command output) do you have and try to set en_US.UTF-8 or something like this explicitly.

P.S. I still don't know if we can (and should/should not) do anything in the project itself to fix this. Later I want to spy stdin/stdout between Java and R in all cases.

**Comment by jbytecode** [comment]
Hi @Kopilov ,

I use `ENV LANG=*` with many values including `en_US.UTF-8` but the problematic test still fails. The output of `locale` command is

`LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
`

**Comment by Kopilov** [comment]
Hi @jbytecode,
I have found main source of the problem with C.UTF-8. In RCaller.exec function we have value  
`String localeAndCharset = join(".", Globals.standardLocale.toString(), Globals.standardCharset.toString());`
and Globals.standardLocale is `Locale.getDefault()`.  
When system locale and LANG environment variable is `C.UTF-8`, Locale.getDefault().toString() returns `en`. It can be used for Java-inside i18n, but exporting LC_ALL and other locale-specific environment variables as `en.UTF-8` is incorrect. So, R changes locale to C. We even can see this in logs, output is
```
SEVERE: R stderr: /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en.UTF-8)
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_COLLATE failed, using "C" 
3: Setting LC_TIME failed, using "C" 
4: Setting LC_MESSAGES failed, using "C" 
5: Setting LC_MONETARY failed, using "C" 
6: Setting LC_PAPER failed, using "C" 
7: Setting LC_MEASUREMENT failed, using "C" 
```

As probably solutions, I have made two patches in different branches (PR are opened). One is changing en.UTF-8 to C.UTF-8. And another is removing any environment changes for R, this works fine for me. The most strange for me is that environment changing was made in patch named [MacOS fixes](https://github.com/jbytecode/rcaller/commit/ca71cbcd5e87a389b2379b5477904da22a6c0851). And test fails in MacOS, primarily…

**Comment by jbytecode** [comment]
@Kopilov have you got any experiences about deploying a jar onto maven central?

**Comment by Kopilov** [comment]
Unfortunately, no.

I have a vacation from November 9 to November 22. May try to look about it in this period.

**Comment by jbytecode** [comment]
sounds good, thank you.

**Comment by Kopilov** [comment]
Hello @jbytecode!
I have successfully deployed my old project [Simple HTTP Client](https://github.com/Kopilov/simple-http-client) to start working with Maven Central. Also I have found old issue in Sonatype Jira about deploying your project by Paul Curcean https://issues.sonatype.org/browse/OSSRH-19298 (as I understand, he is owner of the staging repository in OSSRH at the moment). If you want me to help you with deployment, we have to grant those permissions at Sonatype Nexus to me. I can open new issue in their Jira if need.

**Comment by jbytecode** [comment]
Hi @Kopilov,

Thank you for your great effort. However, Paul is not accessible at this time, we have to find a solution without a help from him. Addition to this, I grant you with any permission for the RCaller repository.

Best.

**Comment by Kopilov** [comment]
@jbytecode [OSSRH-62097](https://issues.sonatype.org/browse/OSSRH-62097) is opened

**Comment by jbytecode** [comment]
It seems it has been resolved!

**Comment by Kopilov** [comment]
RCaller-3.0.2 is just published in Central!
(Version in Globals.java was not changed, sorry… had seen this too late)

**Comment by jbytecode** [comment]
@Kopilov would you like to be granted in rcaller repository?

**Comment by Kopilov** [comment]
Yes, it may be useful in future, thanks!

**Comment by jbytecode** [comment]
@Kopilov you have been granted in the repository. please be careful in future operations.

**Comment by Kopilov** [comment]
Thanks! I have added release commits and tagged RCaller-3.0.2 (that is mapped to Maven Central version and Snapshot removing made for it). But I noticed that there already are v3.0.2 and 3.0.3 tags. Should we remove them?

**Comment by jbytecode** [comment]
up to you! feel free to have changes!

**Comment by jbytecode** [comment]
RCaller is also your project

**Comment by jbytecode** [comment]
is it the right time to close this issue? @Kopilov

**Comment by Kopilov** [comment]
I do not know what a "release tagger" is and whether it it is necessary but at the moment we have made good job. Thank you for this great experience!

**Comment by jbytecode** [comment]
Thank you for your great effort!
