### ISSUE TITLE
What happen with a syntactically wrong R command ?

### ISSUE THREAD

**Issue by mullon-ch** [jbytecode/rcaller#57]
I am new to RCaller, which seems very powerful. When I run the MultipleCalls example, I have no problem. But if I change the syntax of a wrong command (resulting in an R error) for example   :  code.addRCode("result <- sdds(x)"), then the program seems to loop for a while, not taking account of the R generated error. 

Thank you very much.

**Comment by jbytecode** [comment]
thank you for the report. we didn't implement an error-handling mechanism yet. surely it can be done. we will hopefully implement it. any contributions are welcome, if there is any.

**Comment by mullon-ch** [comment]
Thank you for this fast answer. I will have a look to the code.

**Comment by Kopilov** [comment]
Hello,

I have made [the improvement](https://github.com/jbytecode/rcaller/commit/d8b2f6ea36e9ce1084ad930928530aa70b110e1a) in errors handling that allows you to check runtime errors. Now if error is raised in R, it would be thrown to your Java application.

It can be made optional, especially if execution would be slower now (I will test this later).

But another problem still exists. If your code contains unclosed brace, R REPL would wait for next lines (showing `+` in interactive mode) and RCaller still can not validate such situation. May be, we can use `eval` and wrap entire script to string literal.

All these ideas are for `runAndReturnResultOnline` method. `runAndReturnResult` is slower for repeatably usage but it use atomic R calls and controls all correctness by design.

**Comment by Kopilov** [comment]
Added as optional behavior in version 4.0.0

Old behavior is left as default, for backward compatibility and faster executing. The benchmark showed that with VectorSize = 2 median time is 20 ms without tryCatch and 40 ms with tryCatch. With VectorSize = 20000 tryCatch raised median time from 460 ms to 610.

Use `RCaller.runAndReturnResultOnline(String var, boolean addTryCatch)` with addTryCatch = true to enable the feature.

**Comment by mullon-ch** [comment]
Dear Alexandr,

Thank you very much for this improvement. In the next few days, I
will implement this new version of RCaller and have a look at your code. I
will stay in contact with you.

All the best

Christian
