### ISSUE TITLE
RCaller, parser and R version 4

### ISSUE THREAD

**Issue by mullon-ch** [jbytecode/rcaller#66]
I am using RCaller and get results as a xml file with parser.getXMLFile. It was used to work fine. I have updated RCaller version 4.0.2 and it is still working. For one of my colleagues using  R version 4, it appears that instruction parser.getXMLFile() returns null. I have noticed that this command is deprecated. I would like to know if this this issue has been noticed? And if there is is an example where rcaller.parsXMLFile is replaced with rcaller.getIPCResource?

Many thanks

**Comment by jbytecode** [comment]
- @mullon-ch Thank you for your interest on RCaller, we are going to resolve this question.
- @Kopilov would you be willing to handle this issue?

**Comment by mullon-ch** [comment]
Dear Alexandr,

thank you for your fast reaction; I have developed my code on a Mac os
10.15.7 (catalina).  I was using R version 3.7. I have created executables
for mac os, linux and windows, and they were working.

Recently, one of my colleagues has tried to use the program with a Mac
Book Pro M1, mac os Monterey, and R Version 4.0.2 and he got an error
message; after some diagnostics, I identified the command
ROutputParser.getXMLfile as the source of the issue.


Then I wrote the message you are replying to. Since that message, I have
installed on my computer the R version 4.0.2 and the program is working
correctly. I will verify all points to check other possibilities, maybe
related to the speed of the M1 processor (?).

I am using getXMLfile because it was the most common in the RCaller 2.0
version. I have found it quite convenient to deal with different types of R
output (strings, arrays of strings, tables). I will re-write my code with
the getArray and getMatrix functions. I stay interested by examples of
parserOutput other than those in the documentation.

Once again thank you for your support

Christian Mullon




Le mer. 1 déc. 2021 à 12:26, Kopilov Aleksandr ***@***.***> a
écrit :

**Comment by mullon-ch** [comment]
Hi,

The issue I was mentioning has been solved.  It has nothing to do with
RCaller. It comes from the use of R on a Mac with a M1 chip. A specific
version of R.1.2 has to be used. I am sorry for the alarm and I thank you
for your fast reaction.

All the best

Christian

**Comment by Kopilov** [comment]
@mullon-ch Thank you for mentioning.

What about alternative IO examples, I can only show you raw R code snippet that is used in my last R-relatived project. Sharing the whole project is not approved by the customer and employer and I do not have enough time to make good complete example.
Look here https://gist.github.com/Kopilov/5f0e7b66f1da6bbc9ed3e0f818b6ab90
This code is used together with [RCallerPool](https://github.com/Kopilov/RCallerService/tree/master/rcallerpool/src/main/java/com/github/kopilov/rcallerpool):[RDependencies](https://github.com/Kopilov/RCallerService/blob/master/rcallerpool/src/main/java/com/github/kopilov/rcallerpool/RDependencies.kt) and different user-space functions.
I decided not to put this code directly to RCaller because it has absolutely different values matching approach.

**Comment by Kopilov** [comment]
It should be "quite convenient to deal with different types of R output (strings, arrays of strings, tables)" but you have to read Apache Arrow output manually in JVM space
